#
#     ________        _____.__
#     \______   \ _____/ ____\__| ____   ___________ ___.__.
#      |       _// __ \   __\|  |/    \_/ __ \_  __ <   |  |
#      |    |   \  ___/|  |  |  |   |  \  ___/|  | \/\___  |
#      |____|_  /\___  >__|  |__|___|  /\___  >__|   / ____|
#             \/     \/              \/     \/       \/
#
# Made with <3 By DeZeeuw
refinery:
  wool:
    name: "&f&lWool"
    material: WOOL
  terracotta:
    name: "&4&lTerracotta"
    material: TERRACOTTA
  glazed_terracotta:
    name: "&c&lTerracotta"
    material: GLAZED_TERRACOTTA
  stained_glass:
    name: "&7&lStained Glass"
    material: STAINED_GLASS
  stained_glass_pane:
    name: "&b&lStained Glass Pane"
    material: STAINED_GLASS_PANE